### ISSUE TITLE
Issue Report: Ghostery Private Browser failed to install

### ISSUE THREAD

**Issue by Dimi-GE** [ghostery/ghostery-browser-linux-support#10]
Attempting to install the Ghostery browser on MXLinux (Debian 11) using Flakpak leads to an error:

Details from a user after several tries:

**Error message:**

Updating 1/7…**
OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:526:sock_cb: code should not be reached
Bail out! OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:526:sock_cb: code should not be reached
Aborted

**Screenshot:**

![image](https://github.com/user-attachments/assets/1a306929-5c24-4e48-8464-6cf2c7d5d504)

**Comment by philipp-classen** [comment]
Potentially related to https://github.com/flatpak/flatpak/issues/5926

**Comment by philipp-classen** [comment]
Unfortunately, I cannot reproduce.

I tried in a VM with a new MXLinux installation. Installing the Ghostery Browser through Flatpak worked. To install it, I used the MX Package Installer.

**Comment by neb1403** [comment]
I found this online, added it, and it worked:
sudo apt install libcurl3-gnutls=7.88.1-10+deb12u7
